[package]
name = "abc150"
version = "0.1.0"
authors = ["SatoShun <shun.sato1@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
